version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: primecrm-db
    environment:
      POSTGRES_DB: primecrm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - primecrm-data:/var/lib/postgresql/data

volumes:
  primecrm-data:
